import { SponsorType } from "@/components/sponsor/Sponsor";

export const SponsorData: SponsorType[] = [
  // {
  //   type: "image",
  //   src: "/assets/sponsors/prhi.png",
  //   alt: "Pittsburgh Regional Health Initiative",
  //   link: "https://prhi.org/",
  // },
  {
    type: "image",
    src: "/assets/sponsors/College-of-engineering.png",
    alt: "University of Toledo College of Engineering",
    link: "https://www.utoledo.edu/engineering/",
  },
  {
    type: "image",
    src: "/assets/sponsors/eecs.png",
    alt: "University of Toledo Department of Electrical Engineering & Computer Science",
    link: "https://www.utoledo.edu/",
  },
  {
    type: "image",
    src: "/assets/sponsors/spoke.png",
    alt: "SpokeHQ",
    link: "https://spokehq.com/",
  },
  {
    type: "image",
    src: "/assets/sponsors/Nysus-sol.png",
    alt: "Nysus Solutions",
    link: "https://www.nysus.com/",
  },
  {
    type: "image",
    src: "/assets/sponsors/actual-tech.png",
    alt: "Actual Reality Technologies",
    link: "https://www.actualreality.tech/",
  },
  {
    type: "image",
    src: "/assets/sponsors/Koolkat-Science.svg",
    alt: "Koolkat Science",
    link: "https://koolkatscience.net/",
  },
  {
    type: "image",
    src: "/assets/sponsors/mercy.svg",
    alt: "Mercy Health",
    link: "https://www.mercy.com/",
  },
  {
    type: "image",
    src: "/assets/sponsors/firstsolar.png",
    alt: "First Solar",
    link: "https://www.firstsolar.com/",
  },
  {
    type: "image",
    src: "/assets/sponsors/cdw-education.png",
    alt: "CDW",
    link: "https://www.cdw.com/",
  },
  {
    type: "icon",
    icon: "github",
    alt: "GitHub",
    link: "https://www.github.com/",
  },
  { type: "icon", icon: "aws", alt: "AWS", link: "https://aws.amazon.com/" },
  {
    type: "image",
    src: "/assets/sponsors/vercel.png",
    alt: "Vercel",
    link: "https://vercel.com/",
  },
  {
    type: "image",
    src: "/assets/sponsors/codeecho.svg",
    alt: "Code Echo",
    link: "https://codeecho.com/",
  },
  {
    type: "image",
    src: "/assets/sponsors/Perplexity.png",
    alt: "Perplexity AI",
    link: "https://www.perplexity.ai/",
  },
  {
    type: "image",
    src: "/assets/sponsors/Mistral2.png",
    alt: "Mistral AI",
    link: "https://www.mistral.ai/",
  },
  {
    type: "image",
    src: "/assets/sponsors/sprintlogo.png",
    alt: "Sprint.Dev",
    link: "https://www.sprint.dev/",
  },
  {
    type: "image",
    src: "/assets/sponsors/warp.png",
    alt: "Warp Terminal",
    link: "https://www.warp.dev/",
  },
  {
    type: "image",
    src: "/assets/sponsors/orielly.svg",
    alt: "O'Reilly",
    link: "https://www.oreilly.com/",
  },
  {
    type: "image",
    src: "/assets/sponsors/Hugging-face.png",
    alt: "Hugging Face",
    link: "https://huggingface.co/",
  },
  {
    type: "image",
    src: "/assets/sponsors/xyz.svg",
    alt: ".XYZ",
    link: "https://www.gen.xyz/",
  },
  {
    type: "image",
    src: "/assets/sponsors/photoroom.svg",
    alt: "Photoroom",
    link: "https://www.photoroom.com/",
  },
  {
    type: "image",
    src: "/assets/sponsors/standout-stickers.svg",
    alt: "Standout Stickers",
    link: "https://www.standoutstickers.com/",
  },
];
